PLANETS = {
    "mercury": {
        "display_name": "Mercury",
        "color": "#b5b5b5",
        "glow_color": "rgba(181, 181, 181, 0.5)",
        "radius_px": 4,
        "orbit_radius_px": 75,
        "orbit_period_s": 8,
        "orbit_period_days": 87.97,
        "has_rings": False,
        "order": 1,
        # Rich panel data
        "tagline": "The Swift Messenger — a world of extremes at the edge of the Sun",
        "composition": "Iron-nickel core making up 85% of its radius, thin silicate mantle, virtually no atmosphere (trace exosphere of oxygen, sodium, hydrogen). Surface resembles the Moon — ancient craters, scarps, and volcanic plains.",
        "diameter_km": 4879,
        "diameter_vs_earth": 0.383,
        "mass_vs_earth": 0.055,
        "gravity_vs_earth": 0.38,
        "moons": [],
        "day_length_hours": 1407.6,
        "year_length_days": 87.97,
        "avg_temp_c": 167,
        "temp_range": "-180°C to 430°C",
        "distance_from_sun_au": 0.387,
        "notable_features": [
            "Caloris Basin — one of the largest impact craters in the solar system (1,550 km wide)",
            "Enormous cliffs called lobate scarps, some over 3 km tall and hundreds of km long",
            "Water ice confirmed in permanently shadowed polar craters despite proximity to the Sun",
            "A day on Mercury lasts longer than its year",
        ],
        "what_it_feels_like": "Standing on Mercury at noon near the equator, you'd be facing a Sun that appears three times larger than it does from Earth — a scorching disk that hangs almost motionless in a jet-black sky. The temperature beneath your feet could be 430°C, hot enough to melt lead, yet a few meters into the shadow of a crater rim it plunges to -180°C. There is no wind, no weather, no sound. The ground is ancient and cratered, untouched by erosion. If you waited long enough — and a Mercury day lasts 59 Earth days — you'd watch the Sun rise, slow to a halt, reverse direction, then resume. Mercury's eccentric orbit is so extreme that near perihelion, its orbital speed briefly overtakes its rotation, causing the Sun to perform this eerie retrograde dance in the sky.",
        "fun_facts": [
            "Mercury has no moons and no rings",
            "Despite being closest to the Sun, Venus is hotter — Mercury has no atmosphere to trap heat",
            "Mercury shrinks slightly as its iron core cools and contracts",
            "A year on Mercury is just 88 Earth days, but a solar day is 176 Earth days",
        ],
        "exploration": ["Mariner 10 (1974–75) — first flyby", "MESSENGER (2011–15) — first orbit", "BepiColombo (en route, arrival 2025)"],
    },

    "venus": {
        "display_name": "Venus",
        "color": "#e8c97a",
        "glow_color": "rgba(232, 201, 122, 0.5)",
        "radius_px": 7,
        "orbit_radius_px": 110,
        "orbit_period_s": 20,
        "orbit_period_days": 224.7,
        "has_rings": False,
        "order": 2,
        "tagline": "Earth's evil twin — beautiful from afar, lethal up close",
        "composition": "Similar size and rocky composition to Earth, but shrouded in thick CO₂ atmosphere (96.5% CO₂) with clouds of sulfuric acid. Enormous volcanic plains, highland 'continents', and thousands of volcanoes — some possibly still active.",
        "diameter_km": 12104,
        "diameter_vs_earth": 0.949,
        "mass_vs_earth": 0.815,
        "gravity_vs_earth": 0.904,
        "moons": [],
        "day_length_hours": 5832.5,
        "year_length_days": 224.7,
        "avg_temp_c": 465,
        "temp_range": "465°C (day and night — barely varies)",
        "distance_from_sun_au": 0.723,
        "notable_features": [
            "Hottest planet in the solar system despite not being closest to the Sun",
            "Rotates backwards (retrograde) — the Sun rises in the west",
            "Atmospheric pressure 92× Earth's — equivalent to 900m underwater",
            "Maat Mons — an 8 km tall volcano with fresh lava flows detected by Magellan",
            "Brightest natural object in the sky after the Sun and Moon",
        ],
        "what_it_feels_like": "Venus is the closest thing in the solar system to a vision of hell. If you somehow stood on the surface, the first thing you'd notice is the crushing weight of the atmosphere — 92 times Earth's pressure, as if you were nearly a kilometer underwater. The sky above you glows a sickly orange from the thick sulfuric acid clouds that permanently blanket the planet, and the diffuse light is so scattered there are no shadows. The temperature is a constant 465°C — day, night, poles, equator, it doesn't matter. The greenhouse effect is so total that temperature varies by less than 5°C across the entire planet. Soviet landers survived for only about an hour on the surface before being crushed and melted. The landscape itself is alien but familiar: volcanic plains stretching to the horizon, shield volcanoes, and highland continents — Earth's geology running a billion years hotter.",
        "fun_facts": [
            "A day on Venus (243 Earth days) is longer than its year (225 Earth days)",
            "Venus is the only planet (besides Earth) where rainfall exists — but it's sulfuric acid that evaporates before hitting the ground",
            "Venus has more volcanoes than any other planet — over 1,600 major ones",
            "Ancient astronomers thought the Morning Star and Evening Star were two different objects — both are Venus",
        ],
        "exploration": ["Venera 7 (1970) — first soft landing on another planet", "Magellan (1990–94) — radar mapped 98% of surface", "Akatsuki (2015–present) — studying atmosphere"],
    },

    "earth": {
        "display_name": "Earth",
        "color": "#4fc3f7",
        "glow_color": "rgba(79, 195, 247, 0.5)",
        "radius_px": 7,
        "orbit_radius_px": 150,
        "orbit_period_s": 32,
        "orbit_period_days": 365.25,
        "has_rings": False,
        "order": 3,
        "tagline": "The Pale Blue Dot — the only confirmed harbor of life in the universe",
        "composition": "Iron-nickel core generating a protective magnetic field, silicate mantle in convective motion driving plate tectonics, nitrogen-oxygen atmosphere, 71% liquid water surface. The only known planet with plate tectonics, liquid surface water, and life.",
        "diameter_km": 12742,
        "diameter_vs_earth": 1.0,
        "mass_vs_earth": 1.0,
        "gravity_vs_earth": 1.0,
        "moons": [{"name": "The Moon", "note": "Unusually large relative to its host — 1/4 Earth's diameter. Stabilizes Earth's axial tilt, drives ocean tides, and is the only other body humans have visited."}],
        "day_length_hours": 24,
        "year_length_days": 365.25,
        "avg_temp_c": 15,
        "temp_range": "-89°C to 58°C",
        "distance_from_sun_au": 1.0,
        "notable_features": [
            "Only known planet with liquid water on the surface — covering 71% of it",
            "Plate tectonics continuously recycles the crust — no other confirmed tectonically active world",
            "A magnetic field generated by the liquid iron outer core deflects solar wind",
            "The Moon's tidal locking is gradually slowing Earth's rotation — days are getting longer",
            "Life has been found in every environment explored: deep ocean vents, acidic hot springs, stratosphere, permafrost",
        ],
        "what_it_feels_like": "You already know. But consider it from outside: Earth is the rarest kind of place — a world where water exists simultaneously as solid, liquid, and gas, where the temperature has remained stable enough for liquid oceans for 3.8 billion years, where a thin layer of gas just 100 km thick separates you from hard vacuum. From the Moon, Earth appears as a brilliant blue-white marble, impossibly bright against the black. From Mars, it's a bright blue star. From the edge of the solar system, as Voyager 1 photographed it in 1990, it is a pale blue dot — less than a pixel in the frame, suspended in a sunbeam. On that dot, wrote Carl Sagan, is everyone you've ever heard of, every human being who ever lived.",
        "fun_facts": [
            "Earth's core is approximately the same temperature as the surface of the Sun (~5,700°C)",
            "The oceans contain about 99% of the living space on Earth by volume",
            "Earth is the densest planet in the solar system",
            "The oxygen in Earth's atmosphere was produced by photosynthetic life over 2.4 billion years",
        ],
        "exploration": ["Home. 8 billion inhabitants. Over 600 humans have left — only 12 walked on the Moon."],
    },

    "mars": {
        "display_name": "Mars",
        "color": "#c1440e",
        "glow_color": "rgba(193, 68, 14, 0.5)",
        "radius_px": 5,
        "orbit_radius_px": 200,
        "orbit_period_s": 60,
        "orbit_period_days": 686.97,
        "has_rings": False,
        "order": 4,
        "tagline": "The Red Planet — humanity's next frontier, a world that once had rivers",
        "composition": "Iron-oxide (rust) surface giving it the red color, thin CO₂ atmosphere (1% of Earth's pressure), silicate crust, and a mostly solidified iron core. Ancient dried riverbeds, lake beds, and mineral deposits indicate liquid water flowed billions of years ago.",
        "diameter_km": 6779,
        "diameter_vs_earth": 0.532,
        "mass_vs_earth": 0.107,
        "gravity_vs_earth": 0.376,
        "moons": [
            {"name": "Phobos", "note": "Rises in the west, sets in the east 3 times per day. Orbiting so close it will be torn apart by tidal forces in ~50 million years."},
            {"name": "Deimos", "note": "So small and distant it looks like a bright star from Mars' surface. A Martian day passes before Deimos sets."},
        ],
        "day_length_hours": 24.6,
        "year_length_days": 687,
        "avg_temp_c": -63,
        "temp_range": "-143°C to 35°C",
        "distance_from_sun_au": 1.524,
        "notable_features": [
            "Olympus Mons — tallest volcano in the solar system at 21.9 km (nearly 3× Everest)",
            "Valles Marineris — canyon system 4,000 km long, 7 km deep (10× the Grand Canyon)",
            "Polar ice caps of water ice and dry ice that grow and shrink with the seasons",
            "Recurring Slope Lineae — dark streaks suggesting seasonal briny water activity",
            "Dust storms that can engulf the entire planet for months",
        ],
        "what_it_feels_like": "Standing on Mars at noon in summer near the equator, the Sun warms your suit to survivable temperatures. But step into shade and it drops 60°C in minutes. The sky overhead is a dusty butterscotch — not the red many expect, but a pale orange-pink from iron oxide dust suspended in the thin atmosphere. The air pressure is so low that liquid water would instantly boil away — you'd need a pressure suit, always. But you could watch Phobos rise in the west and set in the east, moving visibly across the sky, crossing it in just 4 hours. Olympus Mons is so wide — 600 km across — that if you stood at its base, the caldera would be over the horizon. It wouldn't look like a mountain at all. And somewhere, ancient river deltas and lake beds record a time when Mars was warmer, wetter, and perhaps alive.",
        "fun_facts": [
            "A day on Mars is 24 hours and 37 minutes — almost identical to Earth",
            "Mars has the largest dust storms in the solar system — they can last for months",
            "The Curiosity rover has been driving on Mars since 2012 and is still operational",
            "Mars has two small moons that may be captured asteroids — both are potato-shaped",
        ],
        "exploration": ["Viking 1 & 2 (1976) — first successful landers", "Curiosity (2012–present)", "Perseverance + Ingenuity (2021–present)", "Multiple planned crewed missions 2030s–2040s"],
    },

    "jupiter": {
        "display_name": "Jupiter",
        "color": "#c88b3a",
        "glow_color": "rgba(200, 139, 58, 0.5)",
        "radius_px": 18,
        "orbit_radius_px": 300,
        "orbit_period_s": 120,
        "orbit_period_days": 4332.59,
        "has_rings": True,
        "order": 5,
        "tagline": "The Giant — so massive it almost became a second Sun",
        "composition": "75% hydrogen, 24% helium by mass — essentially a failed star. No solid surface: the atmosphere gradually becomes denser liquid hydrogen, then exotic metallic hydrogen that conducts electricity, then possibly a rocky core. The Great Red Spot is a storm larger than Earth that has raged for at least 350 years.",
        "diameter_km": 139820,
        "diameter_vs_earth": 10.97,
        "mass_vs_earth": 317.8,
        "gravity_vs_earth": 2.528,
        "moons": [
            {"name": "Io", "note": "Most volcanically active body in the solar system — hundreds of active volcanoes, some shooting plumes 300 km high. Tidal flexing by Jupiter's gravity generates the heat."},
            {"name": "Europa", "note": "Smooth ice shell covering a global liquid water ocean twice the volume of all Earth's oceans. One of the best candidates for extraterrestrial life."},
            {"name": "Ganymede", "note": "Largest moon in the solar system — bigger than Mercury. Has its own magnetic field."},
            {"name": "Callisto", "note": "Most heavily cratered object in the solar system — a fossil record stretching back 4 billion years."},
            {"name": "+ 91 more", "note": "Jupiter has 95 confirmed moons — a miniature solar system of its own."},
        ],
        "day_length_hours": 9.93,
        "year_length_days": 4332,
        "avg_temp_c": -110,
        "temp_range": "-145°C (cloud tops) to thousands of degrees (core)",
        "distance_from_sun_au": 5.203,
        "notable_features": [
            "Great Red Spot — an anticyclonic storm 1.3× Earth's diameter, active for 350+ years",
            "Metallic hydrogen in the interior generates the strongest magnetic field of any planet",
            "Jupiter's magnetic field extends 7 million km toward the Sun and past Saturn's orbit away from it",
            "Acts as a 'comet catcher' — its gravity deflects or captures objects that might otherwise hit Earth",
            "Thin ring system discovered by Voyager 1 in 1979",
        ],
        "what_it_feels_like": "There is no surface to stand on. If you descended into Jupiter's atmosphere, you'd fall through increasingly thick bands of cloud — first ammonia crystals, then ammonium hydrosulfide, then water ice, then liquid water. The wind at the cloud tops already roars at 600 km/h. As you fall deeper, the pressure builds. At about 1,000 km down, the pressure is 100,000 times Earth's atmosphere, the temperature exceeds 6,000°C, and hydrogen stops being a gas and starts being a liquid. Keep falling, and that liquid hydrogen transitions into something that exists nowhere else in the universe at large scale: metallic hydrogen — a phase of matter where electrons flow freely, making it as conductive as copper. This is what generates Jupiter's titanic magnetic field. There is no bottom. You would simply be compressed into the planet long before reaching any core.",
        "fun_facts": [
            "Jupiter is 2.5× more massive than all other planets combined",
            "If Jupiter were 80× more massive, it would have ignited as a star",
            "One day on Jupiter is less than 10 hours — it's the fastest-rotating planet",
            "The Shoemaker-Levy 9 comet crashed into Jupiter in 1994 in 21 pieces over 6 days",
        ],
        "exploration": ["Pioneer 10 & 11 (1973–74)", "Voyager 1 & 2 (1979)", "Galileo (1995–2003) — dropped a probe into the atmosphere", "Juno (2016–present) — mapping the interior"],
    },

    "saturn": {
        "display_name": "Saturn",
        "color": "#e4d191",
        "glow_color": "rgba(228, 209, 145, 0.5)",
        "radius_px": 15,
        "orbit_radius_px": 390,
        "orbit_period_s": 200,
        "orbit_period_days": 10759.22,
        "has_rings": True,
        "order": 6,
        "tagline": "Lord of the Rings — the jewel of the solar system",
        "composition": "Hydrogen and helium like Jupiter, but less dense — Saturn would float on water. The iconic rings are made of 90–95% water ice particles ranging from dust grains to house-sized chunks, spanning 282,000 km but averaging only 10–20 meters thick.",
        "diameter_km": 116460,
        "diameter_vs_earth": 9.14,
        "mass_vs_earth": 95.2,
        "gravity_vs_earth": 1.065,
        "moons": [
            {"name": "Titan", "note": "Larger than Mercury. Has a thick nitrogen atmosphere and lakes of liquid methane and ethane on its surface — an alien hydrological cycle with organic chemistry."},
            {"name": "Enceladus", "note": "Sprays geysers of water vapor and ice from its south pole into space, feeding Saturn's E ring. A global liquid water ocean lies beneath its icy crust."},
            {"name": "Mimas", "note": "Heavily cratered with a giant impact crater making it look uncannily like the Death Star."},
            {"name": "+ 143 more", "note": "Saturn has 146 confirmed moons — the most of any planet."},
        ],
        "day_length_hours": 10.66,
        "year_length_days": 10759,
        "avg_temp_c": -140,
        "temp_range": "-185°C (cloud tops)",
        "distance_from_sun_au": 9.537,
        "notable_features": [
            "The rings span 282,000 km — about 3/4 the distance from Earth to the Moon — but are only ~10–20 meters thick",
            "Saturn emits 2.5× more energy than it receives from the Sun — still radiating primordial heat",
            "A hexagonal storm system at the north pole larger than Earth, stable for decades",
            "The Cassini Division — a visible gap in the rings caused by orbital resonance with Mimas",
            "Saturn's density is 0.69 g/cm³ — the only planet less dense than water",
        ],
        "what_it_feels_like": "Like Jupiter, Saturn has no solid surface — you'd fall endlessly into thickening hydrogen. But the experience of orbiting within the ring plane is unlike anything else in the solar system. The rings aren't solid sheets; they're swarms of ice particles, each in its own orbit. From within the gap between the B and C rings, you'd see a flat plane of glittering ice extending to the horizon in both directions, illuminated by distant sunlight, with Saturn's banded disk filling the sky above. The rings are almost impossibly thin — if you scaled Saturn to the size of a basketball, the rings would be thinner than a sheet of paper. Yet they span distances that would dwarf the distance from Earth to the Moon. They are both grand and delicate — and they won't last. In 100 million years, Saturn's gravity will have pulled them all in.",
        "fun_facts": [
            "Saturn's rings are estimated to be only 10–100 million years old — the dinosaurs missed them",
            "Saturn has the fastest winds of any planet — up to 1,800 km/h",
            "Titan is the only moon with a thick atmosphere and surface liquids",
            "The Voyager probes found that Saturn's rotation produces radio emissions — it has a 'sound'",
        ],
        "exploration": ["Pioneer 11 (1979)", "Voyager 1 & 2 (1980–81)", "Cassini-Huygens (2004–17) — 13 years in orbit; Huygens probe landed on Titan"],
    },

    "uranus": {
        "display_name": "Uranus",
        "color": "#7de8e8",
        "glow_color": "rgba(125, 232, 232, 0.5)",
        "radius_px": 11,
        "orbit_radius_px": 470,
        "orbit_period_s": 380,
        "orbit_period_days": 30688.5,
        "has_rings": True,
        "order": 7,
        "tagline": "The Sideways Planet — tilted 98° and rolling through the solar system",
        "composition": "Ice giant — not hydrogen/helium like Jupiter and Saturn, but a hot dense fluid of water, ammonia, and methane ('ices') above a small rocky core. Methane gas in the upper atmosphere absorbs red light, giving Uranus its distinctive cyan color.",
        "diameter_km": 50724,
        "diameter_vs_earth": 3.98,
        "mass_vs_earth": 14.5,
        "gravity_vs_earth": 0.886,
        "moons": [
            {"name": "Miranda", "note": "Has the tallest known cliff in the solar system — Verona Rupes, 20 km high. A fall from its edge would take 12 minutes."},
            {"name": "Ariel", "note": "Youngest surface of Uranus's large moons — relatively fresh craters and valleys."},
            {"name": "Titania", "note": "Largest moon of Uranus — named after the queen of fairies from A Midsummer Night's Dream."},
            {"name": "+ 25 more", "note": "All of Uranus's moons are named after Shakespeare and Alexander Pope characters."},
        ],
        "day_length_hours": 17.24,
        "year_length_days": 30688,
        "avg_temp_c": -195,
        "temp_range": "-224°C (coldest planetary atmosphere in the solar system)",
        "distance_from_sun_au": 19.191,
        "notable_features": [
            "Axial tilt of 97.77° — effectively rolling on its side as it orbits the Sun",
            "Each pole spends 42 years in continuous sunlight, then 42 years in darkness",
            "Coldest planetary atmosphere in the solar system despite not being farthest from Sun",
            "13 known rings, oriented nearly vertically due to the planet's tilt",
            "Something massive struck Uranus early in solar system history — likely causing its extreme tilt",
        ],
        "what_it_feels_like": "Uranus is perhaps the most alien planet to conceptualize because of its tilt. It doesn't rotate the way other planets do — it rolls. Its poles alternately face the Sun for 42-year stretches. If you orbited Uranus's north pole during its summer, you'd see the Sun tracing tight circles overhead for decades while most of the rest of the planet languished in permanent night. Beneath the atmosphere, conditions become increasingly strange. At 5,000 km down, pressures may be high enough that methane breaks down into diamond — and those diamonds may sink as diamond rain toward the core. Uranus is a diamond factory. It is also, despite being billions of kilometers from Earth, technically visible to the naked eye on a dark night — ancient astronomers just thought it was a dim star.",
        "fun_facts": [
            "Uranus was the first planet discovered with a telescope (William Herschel, 1781)",
            "Diamond rain may fall in Uranus's interior — confirmed experimentally in 2017",
            "Uranus radiates almost no excess heat — unlike Jupiter and Saturn, it has cooled off or traps its heat internally",
            "Uranus has been visited by only one spacecraft — Voyager 2 in 1986, for just 5.5 hours",
        ],
        "exploration": ["Voyager 2 (1986) — the only spacecraft to visit; flew past in 5.5 hours", "No dedicated orbiter has ever been sent. A Uranus orbiter is the top priority of the 2023 Planetary Science Decadal Survey."],
    },

    "neptune": {
        "display_name": "Neptune",
        "color": "#4b70dd",
        "glow_color": "rgba(75, 112, 221, 0.5)",
        "radius_px": 10,
        "orbit_radius_px": 540,
        "orbit_period_s": 600,
        "orbit_period_days": 60182.0,
        "has_rings": True,
        "order": 8,
        "tagline": "The Windy World — the most distant planet, and the most violent",
        "composition": "Ice giant like Uranus — a mantle of water, ammonia, and methane ices under crushing pressure, surrounding a rocky core. Methane gives it a deeper blue than Uranus. Has the strongest sustained winds in the solar system despite being so far from the Sun's energy.",
        "diameter_km": 49244,
        "diameter_vs_earth": 3.86,
        "mass_vs_earth": 17.1,
        "gravity_vs_earth": 1.14,
        "moons": [
            {"name": "Triton", "note": "Orbits backwards — the only large moon in the solar system with a retrograde orbit. Almost certainly a captured Kuiper Belt object. Has active nitrogen geysers and is slowly spiraling inward — in 3.6 billion years it will be torn apart."},
            {"name": "Nereid", "note": "One of the most eccentric orbits of any moon — ranges from 1.4 to 9.6 million km from Neptune."},
            {"name": "+ 14 more", "note": "Neptune has 16 known moons."},
        ],
        "day_length_hours": 16.11,
        "year_length_days": 60182,
        "avg_temp_c": -200,
        "temp_range": "-218°C (cloud tops)",
        "distance_from_sun_au": 30.069,
        "notable_features": [
            "Winds up to 2,100 km/h — fastest in the solar system, faster than sound on Earth",
            "The Great Dark Spot observed by Voyager 2 — a storm the size of Earth — had disappeared by 1994",
            "Triton's retrograde orbit means it was captured, not formed in place — a stolen Kuiper Belt world",
            "Neptune generates 2.6× more heat than it receives from the Sun",
            "So far away that sunlight takes 4 hours to reach it, and it appears only 1/900th as bright as from Earth",
        ],
        "what_it_feels_like": "Neptune is the edge of the known solar system — the farthest planet, 4.5 billion km from the Sun. Sunlight there is 900× dimmer than on Earth; the Sun appears as just an extremely bright star, not a disk. Yet somehow Neptune's atmosphere is a cauldron of violence. Winds scream at 2,100 km/h — no other planet comes close. Why? Neptune generates enormous internal heat, perhaps 2.6× what it receives from the Sun, driving these monstrous storms. From orbit, the planet is a deep, rich blue, streaked with white cirrus clouds of methane ice sitting 50 km above the main cloud deck. Below, the pressure builds toward conditions where, as in Uranus, diamond rain may fall. It has been visited exactly once: Voyager 2 swept past in 1989 for a few hours on its way out of the solar system. Everything else we know comes from telescopes. Neptune has not completed a single orbit since its discovery in 1846.",
        "fun_facts": [
            "Neptune was discovered mathematically — astronomers predicted its location from Uranus's wobble before anyone looked",
            "Neptune has not completed a full orbit since it was discovered in 1846 (one orbit = 165 years)",
            "The winds on Neptune move faster than the speed of sound on Earth",
            "Voyager 2 is the only spacecraft to visit — and it passed by in 1989 after a 12-year journey",
        ],
        "exploration": ["Voyager 2 (1989) — only spacecraft ever to visit, 12-year journey", "No follow-up mission has been sent. A Neptune orbiter with Triton lander is under study at NASA."],
    },
}
